### ISSUE TITLE
Markdown from the YAML file requires two newlines

### ISSUE THREAD

**Issue by drewbarontini** [drewbarontini/slidescore#1]
In order to create separate paragraphs and lists in the YAML file, you have to use double newlines.

This doesn't work:

``` yaml
- description: >
    This is the first paragraph.

    This is the second paragraph.
```

But this does:

``` yaml
- description: >
    This is the first paragraph.


    This is the second paragraph.
```

**Comment by romannurik** [comment]
If anyone stumbles across this… in YAML if you use the pipe character `|` instead of `>` it should prevent the parser from collapsing the first newline.

**Comment by drewbarontini** [comment]
@romannurik Interesting! I'll have to try that out.
